- CHANGELOG.md
- README.md
Added dependency badge to `README.md`
> Add dependency badge

- src/file_dialog.rs
Improved API by adding `impl Into<X>` to the window functions.
> Improve API

- CHANGELOG.md
- src/file_dialog.rs
- Added `FileDialog::resizable` to set if the window is resizable
- Added `FileDialog::movable` to set if the window is movable
> Resizable and movable option

- CHANGELOG.md
- src/file_dialog.rs
Added function `FileDialog::title_bar` to enable or disable the title bar.
> Add function to enable or disable the title bar

- CHANGELOG.md
- src/file_dialog.rs
Fixed an issue where the same disk can be loaded multiple times in a row on Windows.
> Fix loading disk on Windows

- CHANGELOG.md
- Cargo.toml
- README.md
Increased versions and updated CHANGELOG.md
> Prepare release v0.2.0

- CHANGELOG.md
Added screenshots of the recent changes to `CHANGELOG.md`
> Add screenshots to CHANGELOG.md

- Cargo.toml
- README.md
Increased package version from `0.2.0` to `0.3.0`.
> Prepare Release v0.3.0

- CHANGELOG.md
- README.md
Added "Pinnable folders" to planned features in `README.md`
> Update planned features

- .github/workflows/rust.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- src/data/directory_content.rs
- src/file_dialog.rs
For more information, see `CHANGELOG.md`.
> Release v0.3.1

- src/config.rs
- src/file_dialog.rs
- src/lib.rs
Moved `FileDialogConfig` to newly created `config.rs` module.
> Move FileDialogConfig to config module

- CHANGELOG.md
- src/config.rs
- src/file_dialog.rs
Implemented `FileDialog::with_config` to initialize a new file dialog directly with a config
> Implement with_config

- CHANGELOG.md
- README.md
I love stats, so I added a crates.io download badge and a total lines of code badge.
> Add download and total lines badge

- CHANGELOG.md
Added missing PR link in `CHANGELOG.md`
> Added missing PR link

- .github/workflows/rust.yml
- CHANGELOG.md
- examples/multilingual/src/main.rs
Updated CI to also test the examples
> Run CI on examples

- CHANGELOG.md
- Cargo.toml
- README.md
Merge branch develop into master.
Release `v0.4.0`
> Merge develop into master

- CHANGELOG.md
- Cargo.toml
- README.md
Increased package version to `v0.5.0` and updated `CHANGELOG.md`
> Prepare release v0.5.0

- CHANGELOG.md
- src/config/labels.rs
- src/config/mod.rs
- src/file_dialog.rs
Moved config module to separate folder and moved `FileDialogLabels` to separate file.
> Restructure config module

- CHANGELOG.md
Documented breaking changes in `CHANGELOG.md`
> Document breaking changes in changelog

- CHANGELOG.md
- src/file_dialog.rs
Internal IDs now use the window ID as the parent ID.
> Improve ID handling

- CHANGELOG.md
- src/file_dialog.rs
- Increased size of path segment buttons
- Increased size of search icon
> Minor UI improvements

- CHANGELOG.md
- src/create_directory_dialog.rs
- src/data/directory_content.rs
- src/data/disks.rs
- src/data/user_directories.rs
- src/file_dialog.rs
Implemented debug for `FileDialog` and member classes.
> Implement debug for FileDialog

- Cargo.toml
https://github.com/fluxxcode/egui-file-dialog/issues/162#issuecomment-2408200586
> Make `default_fonts` opt-out

- src/file_dialog.rs
> implement drag&drop

- README.md
- src/config/keybindings.rs
- src/file_dialog.rs
- src/lib.rs
As per the egui doc for the CMD key:
`On Mac: ⌘ Command key, elsewhere: Ctrl key`
On Mac this works now, please test it on linux/windows before merging.
> Ctrl CMD key bindings

- CHANGELOG.md
- README.md
- Added missing changelog entry for #204 
- Removed only tested on Linux and Windows warning from readme
> docs: update changelog

- CHANGELOG.md
- Cargo.toml
> chore: update sysinfo to v0.33

- CHANGELOG.md
> docs: add missing version tag to changelog

- CHANGELOG.md
- src/data/directory_content.rs
- src/file_dialog.rs
Fixed new Clippy errors added in the latest Rust version
> refactor: fix new clippy errors

- CHANGELOG.md
- Cargo.toml
- README.md
- src/file_dialog.rs
> chore(deps): update egui to v0.31

- CHANGELOG.md
- Cargo.toml
- README.md
Increased package version and updated changelog.
> chore(releases): prepare release v0.9.0

- .github/workflows/rust.yml
- CHANGELOG.md
- examples/multilingual.rs
Forgot to rename main branch in ci
> ci: fix triggering branches

- CHANGELOG.md
- LICENSE
Updated license copyright year and copyright holder
> docs: update license

- src/config/mod.rs
- src/lib.rs
Made `PinnedFolder` struct added in #258 public.
> feat: make pinned folder public

- CHANGELOG.md
- Cargo.toml
Updated `sysinfo` from `0.33` to `0.34`.
> chore(deps): update sysinfo to 0.34

- CHANGELOG.md
- Cargo.toml
Updated sysinfo from version `0.34` to `0.35`
> chore(deps): update sysinfo to v0.35

- CHANGELOG.md
- Cargo.toml
- README.md
- src/file_dialog.rs
This is a follow up PR of #276 
Closes #275 and #274
> refactor: fix deprecation warnings and missing egui version updates

- CHANGELOG.md
- Cargo.toml
- README.md
Updated changelog and increased package version.
> chore(releases): v0.11
