jannistpl/egui-file-dialog

CHANGELOG.md, examples/sandbox/Cargo.toml, examples/save_file/Cargo.toml, examples/select_directory/Cargo.toml, examples/select_file/Cargo.toml
Removed the version of `egui-file-dialog` in the examples.
=> Remove egui-file-dialog version from examples

CHANGELOG.md, README.md
Noticed that there is no syntax highlighting for the example on crates.io. \
I assume that it was because I wrote `rs` instead of `rust` in the code block.
=> Fix syntax highlighting on crates.io

CHANGELOG.md, examples/sandbox/src/main.rs, src/file_dialog.rs
Added new function `FileDialog::anchor` to overwrite the anchor of the window. By default no anchor is set.
Added new private function `FileDialog::create_window` to create the egui window. This allows for more window options in the future.
=> Add function to set window anchor

CHANGELOG.md, src/file_dialog.rs
Added function `FileDialog::title` to overwrite the window title that is used. By default, the title is set dynamically, based on the mode the dialog is in.
=> Add function to overwrite window title

CHANGELOG.md, src/file_dialog.rs
- **BREAKING:** Renamed `FileDialog::default_window_size` to `FileDialog::default_size`
- The name of some window variables has been adjusted for consistency. Now every configuration variable for the window starts with `window_`.
=> Rename window variables

CHANGELOG.md, examples/sandbox/src/main.rs, src/file_dialog.rs
- Added `FileDialog::id` to set the ID of the window
=> Add function to set the ID of the window

CHANGELOG.md, examples/sandbox/src/main.rs, src/file_dialog.rs
- Added `FileDialog::fixed_pos` to set the window to a fixed position
- Added `FileDialog::default_pos` to set the default position of the window
- Removed anchor from sandbox example
=> Add functions to set window position

CHANGELOG.md, src/create_directory_dialog.rs
Previously the problem was that new errors were not visible when creating a new folder. This happened because the error appeared below the folder name input and then didn't scroll down to the error. 
This has now been adjusted so that if there is an error creating a folder, it will scroll to it in the next frame.
=> Fix an issue where no error message appears when creating a folder

CHANGELOG.md, README.md
Updated docs badge to use shields.io instead of docs.rs.
I adjusted this because I noticed that docs.rs no longer offers badges: https://docs.rs/about/badges
=> Updated docs badge to use shields.io

README.md
Forgot to set that the docs badge links to docs.rs ._.
=> Fix link of docs badge

CHANGELOG.md, src/file_dialog.rs
Added functions `FileDialog::min_size` and `FileDialog::max_size` to set the min and max size of the window.
=> Add functions to set min and max window size

CHANGELOG.md, src/file_dialog.rs
Fixed two typos in the documentation.
=> Fix typos in documentation

CHANGELOG.md, README.md
When updating egui I forgot to increase the eframe version in the example in the README.md.
=> Fix eframe version in README.md

CHANGELOG.md, src/create_directory_dialog.rs, src/file_dialog.rs
- Updated the bottom panel so that the dialog can also be resized in `DialogMode::SaveFile` or when selecting a file/directory with a long name
- Here it was necessary to display the error when saving a file as a tooltip when you hover over the grayed out save button.
- Updated file name input that all available space is used
- Added scroll area around the selected item, so that long file or folder names can be displayed without making the dialog larger. 
- The default minimum window size has been further reduced from `(355.0, 200.0)` to `(340.0, 170.0)`
- Added an error icon before the error message when creating a folder.
=> Improve bottom panel

src/file_dialog.rs
Restructured `file_dialog.rs` with multiple `impl` blocks.
=> Restructure file_dialog.rs

CHANGELOG.md, Cargo.toml, README.md
Forgot to update the changelog :D
=> Update CHANGELOG.md for v0.3.0

CHANGELOG.md, src/file_dialog.rs
Adjusted so that the directory that was loaded is automatically used as the selected item. \
This makes it possible to select the shortcut directories such as (Home, Documents) as well as the devices.
=> Fix shortcut directories can not be selected

src/data/directory_content.rs
The problem was that the file name in root directories like "/" was returned as an empty string. This has now been fixed so that the name is displayed correctly for root directories.
=> Fix root directories not displaying correctly

CHANGELOG.md, src/file_dialog.rs
Moved `FileDialog::update` to the open methods. Previously the function was listed last among the getters. However, since it is an important function, it should be listed further up.
=> Move FileDialog::update

CHANGELOG.md, src/file_dialog.rs
Implemented `FileDialog::show_left_panel` to show or hide the left panel with the shortcut directories such as “Home”, “Documents”, etc.
=> Implement FileDialog::show_left_panel

CHANGELOG.md, src/file_dialog.rs
This PR implements `FileDialog::show_places`, `FileDialog::show_devices` and `FileDialog::show_removable_devices` to show or hide the left panel or individual sections.
=> Show and hide individual sections of left panel

CHANGELOG.md, src/file_dialog.rs, src/lib.rs
Moved configuration options of the file dialog to new `FileDialogConfig` struct and implemented `FileDialog::overwrite_config`.
This is useful when you want to configure multiple `FileDialog` objects with the same configuration.
Also removed the `window_` prefix from the window options.
=> Implement file dialog configuration

CHANGELOG.md, src/file_dialog.rs
Implemented `FileDialog::show_top_panel` to show or hide the top panel with the navigation buttons, current path display etc.
=> Implement show_top_panel

CHANGELOG.md, src/file_dialog.rs
Implemented `FileDialog::show_parent_button`, `FileDialog::show_back_button`, `FileDialog::show_forward_button` to show or hide the navigation buttons in the top panel
=> Add show method for navigation buttons

CHANGELOG.md, src/file_dialog.rs
Implemented `FileDialog::show_new_folder_button` to show or hide the button to create a new folder.
=> Implement show_new_folder_button

CHANGELOG.md, src/file_dialog.rs
Implemented `FileDialog::show_current_path` to show or hide the current path in the top panel.
=> Implement show_current_path

CHANGELOG.md, src/file_dialog.rs
Implemented `FileDialog::show_reload_button` to show or hide the reload button in the top panel.
=> Implement show_reload_button

CHANGELOG.md, src/file_dialog.rs
Implemented `FileDialog::show_search` to show or hide the search input in the top panel.
=> Implement show_search

CHANGELOG.md, src/config.rs, src/file_dialog.rs
Implemented `FileDialog::directory_separator` to overwrite the directory separator that is used when displaying the current path.
=> Implement directory_separator

CHANGELOG.md, src/config.rs, src/create_directory_dialog.rs, src/file_dialog.rs, src/lib.rs
Implemented `FileDialogLabels` and `FileDialog::labels` to enable multiple language support.
The following example shows how the default title of the dialog can be displayed in German instead of English.
```rust
use egui_file_dialog::{FileDialog, FileDialogLabels};
let labels_german = FileDialogLabels {
title_select_directory: "📁 Ordner Öffnen".to_string(),
title_select_file: "📂 Datei Öffnen".to_string(),
title_save_file: "📥 Datei Speichern".to_string(),
..Default::default()
};
let file_dialog = FileDialog::new().labels(labels_german);
```
=> Implement FileDialogLabels

CHANGELOG.md, src/config.rs, src/create_directory_dialog.rs, src/file_dialog.rs
Implemented `FileDialog::err_icon`, `FileDialog::folder_icon` and `FileDialog::file_icon` to customize the respective icons. At the moment only unicode is supported.
=> Implement err_icon, folder_icon and file_icon

CHANGELOG.md, src/config.rs, src/file_dialog.rs
Implemented `FileDialog::device_icon` and `FileDialog::removable_device_icon` to overwrite the icon that is used to display devices in the left panel.
=> Customize device icons

CHANGELOG.md, src/data/disks.rs, src/file_dialog.rs
Fixed not every path being canonicalized. This was particularly noticeable on Windows, as not every selected path had the namepsace prefix `\\?\`.
Ref: https://github.com/fluxxcode/egui-file-dialog/issues/59
=> Fix not every path is canonicalized

CHANGELOG.md, src/file_dialog.rs
Implemented `FileDialog::labels_mut` and `FileDialog::config_mut` so we don't have to clone the dialog when updating labels or config.
=> Added labels_mut and config_mut

CHANGELOG.md, src/file_dialog.rs
Changed so the window title is evaluated when updating the dialog. This allows the title to be changed without having to reopen the dialog.
=> Evaluate title when updating dialog

src/file_dialog.rs
Fixed endless window resize when only the current path and the path edit button is visible in the top panel.
=> Fix endless window resize

src/file_dialog.rs
simply clear the search value upon entering another directory.
=> clear `search_value` on dir load

src/file_dialog.rs
Fixes #89 
There are also a few points about when we want to avoid the behavior:
Shift is probably desirable for capitalizing letters, so we want to allow editing while shift is being held down.
This seems to be working.
- The filter string is cleared when a new directory is entered. I think this behavior is desirable because it's much less likely that the user wants to keep the current filter when entering a new directory, rather than wanting to either see the unfiltered contents, or type a new filter from scratch. We could possibly add a way to configure this behavior in the future though.
@aymey made the changes to satisfy the requirements of not activating the behavior. Sorry, your commits got lost because I did a rebase against the latest develop revision.
=> Automatically edit filter string when user is typing

CHANGELOG.md, src/file_dialog.rs
- Fixed the size of the path edit input field because it was too large
- Fixed issue where path edit would not close when the apply path edit button was pressed
=> Fix path edit size and focus

CHANGELOG.md, examples/multilingual/src/main.rs, src/config.rs, src/data/directory_content.rs, src/file_dialog.rs
Implemented the ability to pin folders to the left sidebar and enable or disable the feature with `FileDialog::show_pinned_folders`.
This pull request does not implement persistent storage. Therefore, the pinned folders are deleted after a new `FileDialog` object is created. The feature that the data can be saved persistently will be implemented with a new PR.
https://github.com/fluxxcode/egui-file-dialog/assets/55352293/3df9772f-8bfa-4ac3-a786-9e8866e2e498
Ref: https://github.com/fluxxcode/egui-file-dialog/issues/42
=> Ability to pin folders to the left sidebar

CHANGELOG.md, src/config.rs, src/file_dialog.rs
`FileDialog::overwrite_config` has been deprecated because it is quite confusing to use and provides no value. \
`FileDialog::with_config` and `FileDialog::config_mut` should be used instead.
=> Deprecate FileDialog::overwrite_config

CHANGELOG.md, Cargo.toml, examples/sandbox/Cargo.toml, examples/sandbox/src/main.rs, src/data/directory_content.rs, src/file_dialog.rs, src/lib.rs
Implemented persistent storage with `FileDialog::storage_mut` to save and load the pinned folders.
This requires the new `persistence` feature, which implements `serde::Serialize` and `serde::Deserialize` for the objects to be saved.
Example:
```rust
struct MyApp {
file_dialog: FileDialog,
}
impl MyApp {
pub fn new(cc: &eframe::CreationContext) -> Self {
let mut file_dialog = FileDialog::new();
// Load the file dialog storage
if let Some(storage) = cc.storage {
*file_dialog.storage_mut() =
eframe::get_value(storage, "file_dialog_storage").unwrap_or_default()
}
Self {
file_dialog,
}
}
}
impl eframe::App for MyApp {
fn save(&mut self, storage: &mut dyn eframe::Storage) {
// Save the file dialog storage
eframe::set_value(storage, "file_dialog_storage", self.file_dialog.storage_mut());
}
``` …
=> Implement persistent storage

CHANGELOG.md, src/config.rs, src/file_dialog.rs
Moved storage to `FileDialogConfig` and added methods `FileDialog::storage` and `FileDialogConfig::storage`.
=> Move storage to config and add builder methods

CHANGELOG.md, examples/multilingual/src/main.rs, src/config.rs, src/file_dialog.rs, src/lib.rs, src/modals/mod.rs, src/modals/overwrite_file_modal.rs
Added modal and option `FileDialog::allow_file_overwrite` to allow overwriting an already existing file when the dialog is in `DialogMode::SaveFile` mode.
Modal to ask the user if they really want to overwrite the existing file:
TODO:
Closes #101
=> Add option to overwrite a file

CHANGELOG.md, examples/persistence/Cargo.toml, examples/persistence/README.md, examples/persistence/src/main.rs
Added `persistence` example showing how to save the persistent data of the file dialog.
=> Persistence example

CHANGELOG.md, src/config.rs, src/config/keybindings.rs, src/config/mod.rs, src/create_directory_dialog.rs, src/data/directory_content.rs, src/file_dialog.rs, src/lib.rs, src/modals/mod.rs, src/modals/overwrite_file_modal.rs
Implemented first version of configurable keyboard navigation. \
The following keybindings and their default values have been implemented:
Further todos:
Closes https://github.com/fluxxcode/egui-file-dialog/issues/70
=> Keyboard navigation

CHANGELOG.md, examples/multilingual/src/main.rs, src/config/labels.rs, src/config/mod.rs, src/data/directory_content.rs, src/file_dialog.rs
This PR implements the feature to show or hide hidden files and folders.
For this purpose, the reload button was replaced with a menu button. In the menu you can now find the reload button and the show hidden option.
Changes:
- Added `FileDialog::show_menu_button`
- Added `FileDialog::show_hidden_option`
- Added `show_hidden` to `FileDialogStorage`
- Added `reload` and `show_hidden` to `FileDialogLabels`
=> Hidden files and folders

CHANGELOG.md, src/config/mod.rs, src/file_dialog.rs
Implemented `FileDialog::keep_focus` option, which keeps the file dialog window in focus so that it appears on top of all other windows, even if the user clicks outside the window.
=> Implement keep focus option

CHANGELOG.md, src/config/keybindings.rs, src/create_directory_dialog.rs, src/file_dialog.rs, src/modals/overwrite_file_modal.rs
Implemented the following navigation improvements:
- Selection keybindings now break out of text input fields
- Path editing is automatically closed when submitting
- When changing the search input, the first item is automatically selected
- When closing the search input with Enter, the file dialog attempts to submit the current selection
- Enter now selects the current directory if no other item is currently selected
=> Improve navigation

Cargo.toml, examples/persistence/README.md, src/config/mod.rs, src/data/directory_content.rs
The `persistence` feature has been renamed to `serde` because it currently only implements `serde::Serialize` and `serde::Deserialize` for the persistent data.
=> Rename persistence feature to serde

CHANGELOG.md, src/config/mod.rs, src/file_dialog.rs
By default the file dialog is now displayed as modal. This will display an overlay under the window and disable interaction outside of the window. The modal can be deactivated with `FileDialog::as_modal` and the color of the modal overlay can be adjusted with `FileDialog::modal_overlay_color`.
Closes #117
=> Implement modal option

src/data/directory_content.rs, src/lib.rs
It's already a public struct, but it's not reachable publicly, so it's not possible to for example construct an instance of it.
This commit makes it publically reachable by re-exporting it in the crate root, and also adds a missing doc string for `is_hidden`.
=> Make DirectoryEntry publicly reachable

CHANGELOG.md, examples/multilingual/src/main.rs, examples/sandbox/src/main.rs, src/config/labels.rs, src/config/mod.rs, src/data/directory_content.rs, src/file_dialog.rs
This PR implements `FileDialog::add_file_filter` which allows adding file filters from the backend, selectable by the user from a dropdown in the bottom right.
Additionally, `FileDialog::default_file_filter` has been implemented to set a file filter that is selected by default.
Example:
```rust
let file_dialog = FileDialog::default()
.add_file_filter("PNG files", Arc::new(|p| p.extension().unwrap_or_default() == "png"))
.add_file_filter("TOML files", Arc::new(|p| p.extension().unwrap_or_default() == "toml"))
.add_file_filter("Rust source files", Arc::new(|p| p.extension().unwrap_or_default() == "rs"))
.default_file_filter("TOML files");
```
Ref: #122
=> Implement file filters

src/config/keybindings.rs, src/file_dialog.rs
Added new shortcut `~` that loads the home directory and begins text editing of the current path.
Since eframe only handles this keyboard input as a text event, the new keybinding type `Text` was added.
Ref #116
=> Home directory shortcut

CHANGELOG.md, examples/multilingual/src/main.rs, examples/sandbox/src/main.rs, src/config/keybindings.rs, src/config/labels.rs, src/data/directory_content.rs, src/file_dialog.rs
Implemented feature to select multiple files and folders at once.
Breaking Changes:
- Added `DialogMode::SelectMultiple`
- Added `DialogState::SelectedMultiple`
- Added new labels to `FileDialogLabels`
- Removed `PartialEq, Eq` implementation from `DirectoryEntry`, use `DirectoryEntry::path_eq` instead
Non breaking changes:
- Added `FileDialog::select_multiple`
- Added `FileDialog::selected_multiple`
- Added `FileDialog::take_selected_multiple`
- Added Keybinding `select_all`
=> Implement multi selection

src/config/mod.rs, src/file_dialog.rs
File Dialog doesnt implement the Send Bound. this is not a bug but limiting the use of FileDialog.
Not beeing Send means that it can not be used in a Mutex or across multiple threads.
I found this restriction unnecessaryly strict and changed it.
this only required a few trait bounds to be changed, nothing else in the source code.
please feel free to merge this request.
=> File Dialog doesnt implement the Send Bound

Cargo.toml
Enabled `persistence` feature for `eframe`.
Ref: #133
=> Fix persistence in examples

CHANGELOG.md, src/lib.rs
Updated crate documentation in `lib.rs`
=> Update crate documentation

CHANGELOG.md, Cargo.toml, README.md
See `CHANGELOG.md` for more information
=> Prepare release v0.6.0

CHANGELOG.md, src/file_dialog.rs
Fixed that the `select_all` keybinding can also be used in the `DialogMode`'s in which only one item can be selected.
=> Fix select_all keybinding

CHANGELOG.md, src/file_dialog.rs
Fixed the file dialog window resizing endlessly if the name of the selected file filter is larger than the dropdown menu itself.
=> Fix endless resize of file dialog window

CHANGELOG.md, src/file_dialog.rs
When the dialog is used to select a file, the path edit is now selected if the specified path is a file.
Closes: #150
=> Select file from path edit

Cargo.toml, examples/sandbox/src/main.rs, src/data/directory_content.rs, src/file_dialog.rs
Also fixes some deprecations and lints
- The save file dialog in the example seems to keep expanding unbounded.
Gonna have to look into the cause of that.
=> Update to egui 0.29

CHANGELOG.md, src/config/mod.rs, src/file_dialog.rs
When the dialog is in file save mode, the path edit is used as the expected file to save if:
- an extension is specified,
- the path is not an existing directory,
- and the parent path exists.
Closes #159
=> Save path from path edit

CHANGELOG.md, src/data/directory_content.rs, src/file_dialog.rs
Changed so that the file filter and "show hidden files option" are applied when the directory loads rather than every frame. This should improve performance, especially on Windows.
The text search is  still applied every frame. Implementing this differently is not easy either. We can't reload the directory every time the text field changes, otherwise the usability will suffer, especially for large directories and slow disks.
However, with 50,000 items in a directory, there will be no significant performance issues if this is done every frame.
Ref #168
=> Filter directory when loading

examples/custom-right-panel/Cargo.toml, examples/custom-right-panel/src/main.rs, src/file_dialog.rs
- `active_entry`: Gives access to the `selected_item` field. It allows the user to know what is the currently highlighted file, or currently active directory in absence of a highlighted file.
- `update_with_custom_right_panel`: Does the same thing as `update`, except it also adds a right panel with a custom ui callback to allow the user to show custom information, or open options.
=> Add `FileDialog::{active_entry, update_with_custom_right_panel}`

src/config/mod.rs, src/data/directory_content.rs, src/file_dialog.rs
- Fixed directory filters not being applied using user directory shortcuts
- Further Cleanup directory content
- Removed different default values for `FileDialogConfig::show_system_files_option`
=> Fix directory filters not being applied using user directory shortcuts

CHANGELOG.md, src/file_dialog.rs
Fixed heading places could not be updated using `FileDialogLabels`.
Closes #179
=> Fix heading places

CHANGELOG.md, src/data/directory_content.rs, src/file_dialog.rs
This PR implements the first iteration of only updating visible items inside the central panel.
Now all items are only updated if the text filter is not empty or the create directory dialog is open.
Ref #168
=> Only update visible items when search value is empty

README.md
Added missing system file option entry in data to be saved permanently.
=> docs: add system file option to persistent data

.github/workflows/rust.yml, .typos.toml, src/config/keybindings.rs, src/data/directory_content.rs, src/file_dialog.rs
To improve the workflows I did the following:
- Checks and build now running on macOS, Windows and Ubuntu to check for all systems
- Check with `cargo machete` for unused crates
- Check for typos with `typos-cli`
- Add some typos which should be ignored as they are in german
- Fix some typos
=> ci: improve workflows

src/file_dialog.rs
Fixed that when creating a new folder using the UI button, the folder was created but the directory contents were not updated.
This was a bug introduced with: https://github.com/fluxxcode/egui-file-dialog/pull/181
=> fix: new folder dialog not updating content

CHANGELOG.md, Cargo.toml, src/data/disks.rs, src/file_dialog.rs
This PR adds support for Windows mapped network devices. However, this is more of a temporary implementation until `sysinfo` provides functionality for mapped network devices on Windows.
Ref: #168
=> feat: windows mapped network devices

src/data/disks.rs
this addresses https://github.com/fluxxcode/egui-file-dialog/issues/168 for macOS.
It still shows my removable drive twice, for some reason, so this bug is still there. But network drives are available and Macintosh HDD is not shown twice anymore.
Figure: "Space" is a network drive mounted via SMB
EDIT: messed up the rebase on the other PR, so closed it and opened up this one
=> show network drives on macOS

src/file_dialog.rs
This adresses #196.
However, in the current state the UI will not scroll to the selected (dropped) item. Even though `self.scroll_to_selection = true;`is set. Any ideas?
=> select dropped item

src/file_dialog.rs
Fixed scroll to selection having no effect. This is a bug that was introduced with https://github.com/fluxxcode/egui-file-dialog/pull/181
Also cleanup dropped files.
Ref: https://github.com/fluxxcode/egui-file-dialog/pull/197
=> fix: scroll to selection

src/file_dialog.rs
Fixed slightly incorrect item height when using `ScrollArea::show_rows`.
Closes #200
=> fix: item height in show_rows

src/data/disks.rs
This addresses #201 and only shows Macintosh HD once as `/`
=> Fix Macintosh HD

README.md
Fixed incorrect formatting of keybindings table in `README.md`
=> docs: fix formatting of keybindings in readme

CHANGELOG.md
Fixed formatting in changelog... again (╯°□°)╯︵ ┻━┻
=> docs: fix formatting in changelog

CHANGELOG.md, examples/custom_right_panel.rs, examples/multiple_actions.rs, examples/sandbox.rs, src/file_dialog.rs, src/information_panel.rs, src/lib.rs
This PR implements the last changes to consistent public API naming. For more information see: #171 and #207.
Changes:
- Removed in #207 deprecated methods: `select_directory`, `select_file`, `select_multiple`, `overwrite_config`, `selected`, `take_selected`, `take_selected_multiple` 
- Renamed `DialogMode`'s: `SelectFile` -> `PickFile`, `SelectDirectory` -> `PickDirectory`, `SelectMultiple` -> `PickMultiple`
- Renamed `DialogState`s: `Selected` -> `Picked`, `SelectedMultiple` -> `PickedMultiple`
- Renamed `active_entry` -> `selected_entry`
- Renamed `active_selected_entries` -> `selected_entries`
Related PR: #207 
Closes #171
=> rework!: consistent api naming

CHANGELOG.md, Cargo.toml
Updated `directories` dependency from `v0.5.0` to `v0.6.0`
=> chore: update directories

CHANGELOG.md, src/data/disks.rs, src/file_dialog.rs
Fixed canonicalization flag (`FileDialog::canonicalize_paths`) not being used when initializing the file dialog object.
With this PR, the file dialog is now only updated when the `open` method is called and not when the object is initialized.
Ref: #236
=> fix: canonicalization flag not used during object creation

CHANGELOG.md, src/config/mod.rs, src/file_dialog.rs, src/lib.rs
This PR adds a new configuration option `opening_mode` which allows to further specify which directory is loaded when the file dialog is opened.
Currently the following options are available:
- `OpeningMode::AlwaysInitialDir`: The configured initial directory (`FileDialog::initial_directory`) should always be opened
- `OpeningMode::LastVisitedDir`: The directory most recently visited by the user should be opened regardless of whether anything was picked
- `OpeningMode::LastPickedDir`: The last directory from which the user picked an item should be opened
Which directory was last visited and from which directory the user selected an item is stored in `FileDialogStorage`. This allows the initial directory to be retained even when the application restarts.
Closes #215
=> feat!: opening mode

CHANGELOG.md, examples/multiple_actions.rs, src/file_dialog.rs
Removed result from `FileDialog::open`. Since #177 we don't know the result of loading the initial directory because it is done asynchronously
=> refactor!: remove result from open method

examples/custom_filesystem.rs, src/file_dialog.rs, src/file_system.rs
Fixed issue on my part. When I reviewed #227  I assumed that `FileSystem::with_file_system` should be a builder method. However, because of the initial directory, this has to be a creation function.
This is not a breaking change since the latest version does not yet include the file system abstraction.
=> refactor: fix file system creation method

CHANGELOG.md, src/config/labels.rs, src/config/mod.rs, src/file_dialog.rs
This PR adds a new shortcut button to the hamburger menu, allowing to quickly open the current working directory returned by `std::env::current_dir`. The button can be disabled using `FileDialog::show_working_directory_button`.
=> feat: working directory shortcut

src/file_dialog.rs
Fixed the `Go to Working Directory` shortcut added with #246 not using the virtual file system.
=> fix: use virtual file system to retrieve the current working directory

CHANGELOG.md, examples/multilingual.rs, examples/sandbox.rs, src/config/labels.rs, src/config/mod.rs, src/data/directory_content.rs, src/file_dialog.rs
This PR adds the new methods `FileDialog::add_save_extension`, `FileDialogConfig::add_save_extension` and `FileDialog::default_save_extension` which allow adding a file extension that will be shown to the user in a dropdown list when saving a file. This also automatically adds the file extension to the file name input.
For example:
```rust
FileDialog::new()
.add_save_extension("Picture", "png")
.add_save_extension("Rust Source File", "rs")
.add_save_extension("Configuration File", "toml")
.default_save_extension("Picture");
```
Will create the following options with "Picture" beeing selected by default.
Further changes:
- Changed the default file name from an empty string to `Untitled`
- Automatically highlight file name
TODO:
Closes #138
=> feat: implement extension filter when saving a file

CHANGELOG.md, examples/multilingual.rs, src/config/labels.rs, src/config/mod.rs, src/file_dialog.rs
This PR now allows renaming a pinned folder via the context menu.
Currently saved pinned folders will be deleted, however, because the `FileDialogStorage` has changed and is no longer compatible with previously saved data.
Closes #251
=> feat!: ability to rename pinned folder

CHANGELOG.md, src/config/mod.rs, src/data/directory_content.rs, src/data/mod.rs, src/file_dialog.rs, src/lib.rs
Removed `FileDialogStorage` from `FileDialogConfig` because I find it more user-friendly and logical to have the configuration and storage separate. Typically, there's only one `FileDialogStorage` in the application, although you may want to use several different configurations. If the storage is in the configuration, you'll need access to the file dialog wherever you create a configuration.
=> refactor!: move storage out of config

CHANGELOG.md, examples/sandbox.rs, src/config/mod.rs, src/file_dialog.rs
Added new shortcut methods `FileDialog::add_file_filter_extensions` and `FileDialogConfig::add_file_filter_extensions`  which allow adding a filter matching specific file extensions.
Example:
```rust
FileDialog::new()
.add_file_filter_extensions("Pictures", vec!["png", "jpg", "dds"]);
```
Closes #261
=> feat: add shortcut add_file_filter_extensions

Cargo.toml
Include and exclude fields have been corrected, as currently only the fields specified in the include directive were included. All other files, including the source, were incorrectly excluded.
=> fix: package include and exclude fields

examples/multiple_actions.rs, src/file_dialog.rs
Using strings for a (most likely) finite set of operations doesn't feel very Rusty.
A user could instead define their own enum that they can do an exhaustive match over. The problem is how to integrate this into the FileDialog API without making things convoluted with generic parameters and whatnot.
This commit goes for an approach using std::any::Any, and downcasting the user data into the requested type when the user data is queried.
=> Replace operation_id with custom user_data

src/file_dialog.rs
While testing custom file systems, I realized that the user is unable to create directories properly because the CreateDirectoryDialog always holds a reference to NativeFileSystem. This solves the problem by making sure that the dialog is updated when FileDialog is created from filesystem or config
=> Create directory dialog uses correct file system

CHANGELOG.md, src/file_dialog.rs
This MR fixes the unexpected behavior that user data is deleted when the file dialog is reset.
Closes #284
=> fix!: prevent user data from being cleared when file dialog is reset
